import { BudgetPrice } from './types'

export const DEFAULT_PRICE_DATABASE: BudgetPrice[] = [
  {
    id: '1',
    code: 'E02CM010',
    description: 'M2. Excavación de zanjas en terrenos compactos',
    unit: 'm2',
    unitPrice: 5.25,
    type: 'unit',
    category: 'Movimiento de tierras',
    subcategory: 'Excavaciones',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '2',
    code: 'E04AB020',
    description: 'M3. Hormigón HA-25/B/20/IIa fabricado en central',
    unit: 'm3',
    unitPrice: 85.50,
    type: 'material',
    category: 'Cimentación',
    subcategory: 'Hormigones',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '3',
    code: 'E04AB110',
    description: 'KG. Acero corrugado B 500 S en barras',
    unit: 'kg',
    unitPrice: 1.15,
    type: 'material',
    category: 'Cimentación',
    subcategory: 'Aceros',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '4',
    code: 'E04LE010',
    description: 'M2. Encofrado y desencofrado de zapatas',
    unit: 'm2',
    unitPrice: 18.75,
    type: 'unit',
    category: 'Cimentación',
    subcategory: 'Encofrados',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '5',
    code: 'E07LCA010',
    description: 'M2. Fábrica de ladrillo cerámico perforado 24x11.5x9 cm',
    unit: 'm2',
    unitPrice: 32.50,
    type: 'unit',
    category: 'Albañilería',
    subcategory: 'Fábricas',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '6',
    code: 'E07LHD010',
    description: 'M2. Tabique de ladrillo hueco doble 7x24x11.5 cm',
    unit: 'm2',
    unitPrice: 18.90,
    type: 'unit',
    category: 'Albañilería',
    subcategory: 'Tabiques',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '7',
    code: 'E08PFM010',
    description: 'M2. Enfoscado maestreado con mortero de cemento',
    unit: 'm2',
    unitPrice: 12.35,
    type: 'unit',
    category: 'Revestimientos',
    subcategory: 'Enfoscados',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '8',
    code: 'E08RCE010',
    description: 'M2. Alicatado con azulejo 20x20 cm',
    unit: 'm2',
    unitPrice: 28.60,
    type: 'unit',
    category: 'Revestimientos',
    subcategory: 'Alicatados',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '9',
    code: 'E08RSO010',
    description: 'M2. Solado de gres porcelánico 60x60 cm',
    unit: 'm2',
    unitPrice: 45.80,
    type: 'unit',
    category: 'Pavimentos',
    subcategory: 'Solados',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '10',
    code: 'E09CPA010',
    description: 'M2. Falso techo continuo de placas de yeso laminado',
    unit: 'm2',
    unitPrice: 24.50,
    type: 'unit',
    category: 'Falsos techos',
    subcategory: 'Continuos',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '11',
    code: 'E13CJA010',
    description: 'M2. Carpintería de aluminio lacado con RPT',
    unit: 'm2',
    unitPrice: 285.00,
    type: 'unit',
    category: 'Carpintería',
    subcategory: 'Aluminio',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '12',
    code: 'E13CMA010',
    description: 'M2. Puerta de paso ciega de madera 203x82.5x3.5 cm',
    unit: 'ud',
    unitPrice: 195.00,
    type: 'unit',
    category: 'Carpintería',
    subcategory: 'Madera',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '13',
    code: 'E14LSC010',
    description: 'M2. Vidrio laminar de seguridad 4+4 mm',
    unit: 'm2',
    unitPrice: 38.50,
    type: 'material',
    category: 'Vidriería',
    subcategory: 'Vidrios',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '14',
    code: 'E15ACS010',
    description: 'UD. Inodoro de porcelana blanco con cisterna',
    unit: 'ud',
    unitPrice: 165.00,
    type: 'unit',
    category: 'Fontanería',
    subcategory: 'Aparatos sanitarios',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '15',
    code: 'E15ACL010',
    description: 'UD. Lavabo de porcelana blanco con pedestal',
    unit: 'ud',
    unitPrice: 125.00,
    type: 'unit',
    category: 'Fontanería',
    subcategory: 'Aparatos sanitarios',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '16',
    code: 'E15TPC010',
    description: 'M. Tubería de PVC sanitario Ø110 mm',
    unit: 'm',
    unitPrice: 12.80,
    type: 'unit',
    category: 'Fontanería',
    subcategory: 'Tuberías',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '17',
    code: 'E16IEL010',
    description: 'UD. Punto de luz sencillo con tubo PVC Ø20 mm',
    unit: 'ud',
    unitPrice: 42.50,
    type: 'unit',
    category: 'Electricidad',
    subcategory: 'Instalación',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '18',
    code: 'E16IET010',
    description: 'UD. Punto de toma de corriente con tubo PVC Ø20 mm',
    unit: 'ud',
    unitPrice: 38.90,
    type: 'unit',
    category: 'Electricidad',
    subcategory: 'Instalación',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '19',
    code: 'E16CCP010',
    description: 'UD. Cuadro de protección ICP 40A + 10 PIAS',
    unit: 'ud',
    unitPrice: 325.00,
    type: 'unit',
    category: 'Electricidad',
    subcategory: 'Cuadros',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '20',
    code: 'E17CAL010',
    description: 'UD. Caldera mural de condensación 24 kW',
    unit: 'ud',
    unitPrice: 1850.00,
    type: 'unit',
    category: 'Climatización',
    subcategory: 'Generación',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '21',
    code: 'E17RAD010',
    description: 'UD. Radiador de aluminio 600 mm 6 elementos',
    unit: 'ud',
    unitPrice: 185.00,
    type: 'unit',
    category: 'Climatización',
    subcategory: 'Emisión',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '22',
    code: 'E18AIS010',
    description: 'M2. Aislamiento térmico de lana mineral 60 mm',
    unit: 'm2',
    unitPrice: 8.75,
    type: 'material',
    category: 'Aislamientos',
    subcategory: 'Térmicos',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '23',
    code: 'E18IMP010',
    description: 'M2. Impermeabilización de cubierta con lámina asfáltica',
    unit: 'm2',
    unitPrice: 18.50,
    type: 'unit',
    category: 'Impermeabilizaciones',
    subcategory: 'Cubiertas',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '24',
    code: 'E19PIN010',
    description: 'M2. Pintura plástica lisa color blanco',
    unit: 'm2',
    unitPrice: 6.80,
    type: 'unit',
    category: 'Pintura',
    subcategory: 'Interiores',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '25',
    code: 'E01OF010',
    description: 'H. Oficial 1ª construcción',
    unit: 'h',
    unitPrice: 22.50,
    type: 'labor',
    category: 'Mano de obra',
    subcategory: 'Oficial',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '26',
    code: 'E01PE010',
    description: 'H. Peón ordinario construcción',
    unit: 'h',
    unitPrice: 18.75,
    type: 'labor',
    category: 'Mano de obra',
    subcategory: 'Peón',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '27',
    code: 'E01MR010',
    description: 'H. Maquinaria retroexcavadora sobre neumáticos',
    unit: 'h',
    unitPrice: 45.00,
    type: 'machinery',
    category: 'Maquinaria',
    subcategory: 'Movimiento de tierras',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '28',
    code: 'E01MC010',
    description: 'H. Maquinaria camión volquete',
    unit: 'h',
    unitPrice: 38.50,
    type: 'machinery',
    category: 'Maquinaria',
    subcategory: 'Transporte',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '29',
    code: 'E22SEG010',
    description: 'PA. Seguridad y salud',
    unit: 'pa',
    unitPrice: 2500.00,
    type: 'unit',
    category: 'Seguridad y salud',
    subcategory: 'General',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  },
  {
    id: '30',
    code: 'E23GES010',
    description: 'PA. Gestión de residuos',
    unit: 'pa',
    unitPrice: 1200.00,
    type: 'unit',
    category: 'Gestión de residuos',
    subcategory: 'General',
    lastUpdated: Date.now(),
    source: 'BEDEC'
  }
]

export const PRICE_CATEGORIES = [
  'Movimiento de tierras',
  'Cimentación',
  'Estructura',
  'Albañilería',
  'Revestimientos',
  'Pavimentos',
  'Falsos techos',
  'Carpintería',
  'Vidriería',
  'Fontanería',
  'Electricidad',
  'Climatización',
  'Aislamientos',
  'Impermeabilizaciones',
  'Pintura',
  'Mano de obra',
  'Maquinaria',
  'Seguridad y salud',
  'Gestión de residuos'
]
